apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shell-user
rules:
  - apiGroups:
      - ""
    resourceNames:
      - cliapp-shell-context
    resources:
      - configmaps
    verbs:
      - list
      - get
      - watch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shell-context-all-allowed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cliapp-shell-user
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts
