/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	cliappv1 "github.com/warm-metal/cliapp/pkg/apis/cliapp/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCliApps implements CliAppInterface
type FakeCliApps struct {
	Fake *FakeCliappV1
	ns   string
}

var cliappsResource = schema.GroupVersionResource{Group: "cliapp", Version: "v1", Resource: "cliapps"}

var cliappsKind = schema.GroupVersionKind{Group: "cliapp", Version: "v1", Kind: "CliApp"}

// Get takes name of the cliApp, and returns the corresponding cliApp object, and an error if there is any.
func (c *FakeCliApps) Get(ctx context.Context, name string, options v1.GetOptions) (result *cliappv1.CliApp, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cliappsResource, c.ns, name), &cliappv1.CliApp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cliappv1.CliApp), err
}

// List takes label and field selectors, and returns the list of CliApps that match those selectors.
func (c *FakeCliApps) List(ctx context.Context, opts v1.ListOptions) (result *cliappv1.CliAppList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cliappsResource, cliappsKind, c.ns, opts), &cliappv1.CliAppList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &cliappv1.CliAppList{ListMeta: obj.(*cliappv1.CliAppList).ListMeta}
	for _, item := range obj.(*cliappv1.CliAppList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cliApps.
func (c *FakeCliApps) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cliappsResource, c.ns, opts))

}

// Create takes the representation of a cliApp and creates it.  Returns the server's representation of the cliApp, and an error, if there is any.
func (c *FakeCliApps) Create(ctx context.Context, cliApp *cliappv1.CliApp, opts v1.CreateOptions) (result *cliappv1.CliApp, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cliappsResource, c.ns, cliApp), &cliappv1.CliApp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cliappv1.CliApp), err
}

// Update takes the representation of a cliApp and updates it. Returns the server's representation of the cliApp, and an error, if there is any.
func (c *FakeCliApps) Update(ctx context.Context, cliApp *cliappv1.CliApp, opts v1.UpdateOptions) (result *cliappv1.CliApp, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cliappsResource, c.ns, cliApp), &cliappv1.CliApp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cliappv1.CliApp), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCliApps) UpdateStatus(ctx context.Context, cliApp *cliappv1.CliApp, opts v1.UpdateOptions) (*cliappv1.CliApp, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(cliappsResource, "status", c.ns, cliApp), &cliappv1.CliApp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cliappv1.CliApp), err
}

// Delete takes name of the cliApp and deletes it. Returns an error if one occurs.
func (c *FakeCliApps) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(cliappsResource, c.ns, name), &cliappv1.CliApp{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCliApps) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cliappsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &cliappv1.CliAppList{})
	return err
}

// Patch applies the patch and returns the patched cliApp.
func (c *FakeCliApps) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *cliappv1.CliApp, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cliappsResource, c.ns, name, pt, data, subresources...), &cliappv1.CliApp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cliappv1.CliApp), err
}
