apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-image-warm-metal
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: plugin
          volumeMounts:
            - mountPath: /var/lib/containerd
              name: snapshot-home
      volumes:
        - hostPath:
            path: /var/lib/containerd
            type: Directory
          name: snapshot-home
