# permissions for end users to view cliapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cliapp-viewer-role
rules:
- apiGroups:
  - core.cliapp.warm-metal.tech
  resources:
  - cliapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.cliapp.warm-metal.tech
  resources:
  - cliapps/status
  verbs:
  - get
