# permissions for end users to edit cliapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cliapp-editor-role
rules:
- apiGroups:
  - core.cliapp.warm-metal.tech
  resources:
  - cliapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.cliapp.warm-metal.tech
  resources:
  - cliapps/status
  verbs:
  - get
