/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	cliappv1 "github.com/warm-metal/cliapp/pkg/apis/cliapp/v1"
	versioned "github.com/warm-metal/cliapp/pkg/clientset/versioned"
	internalinterfaces "github.com/warm-metal/cliapp/pkg/informers/externalversions/internalinterfaces"
	v1 "github.com/warm-metal/cliapp/pkg/listers/cliapp/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CliAppInformer provides access to a shared informer and lister for
// CliApps.
type CliAppInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.CliAppLister
}

type cliAppInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCliAppInformer constructs a new informer for CliApp type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCliAppInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCliAppInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCliAppInformer constructs a new informer for CliApp type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCliAppInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CliappV1().CliApps(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CliappV1().CliApps(namespace).Watch(context.TODO(), options)
			},
		},
		&cliappv1.CliApp{},
		resyncPeriod,
		indexers,
	)
}

func (f *cliAppInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCliAppInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *cliAppInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cliappv1.CliApp{}, f.defaultInformer)
}

func (f *cliAppInformer) Lister() v1.CliAppLister {
	return v1.NewCliAppLister(f.Informer().GetIndexer())
}
