debug = true
# root is where all buildkit state is stored.
root = "/var/lib/buildkit"
local-mount-source-root = "/var/lib/buildkit/local-mnt-src"
# insecure-entitlements allows insecure entitlements, disabled by default.
insecure-entitlements = [ "network.host", "security.insecure" ]

[grpc]
  address = [ "unix:///run/buildkit/buildkitd.sock", "tcp://0.0.0.0:2375" ]
  uid = 0
  gid = 0

[worker.oci]
  enabled = false

[worker.containerd]
  address = "/run/containerd/containerd.sock"
  enabled = true
  platforms = [ "linux/amd64", "linux/arm64", "linux/arm/v7", "linux/arm/v6", "linux/riscv64", "linux/ppc64le", "linux/s390x", "linux/386", "linux/mips64le", "linux/mips64" ]
  namespace = "k8s.io"
  gc = true
  [[worker.containerd.gcpolicy]]
    keepBytes = 10240000000
    keepDuration = 3600