apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-image-warm-metal
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: plugin
          volumeMounts:
          - name: snapshot-home
            mountPath: /mnt/vda1/var/lib/containerd
      volumes:
      - hostPath:
          path: /mnt/vda1/var/lib/containerd
          type: Directory
        name: snapshot-home
